export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-900 via-blue-950 to-slate-900 flex items-center justify-center px-6">
      <div className="text-center max-w-2xl w-full">
        {/* Logo / Icon */}
        <div className="text-7xl mb-6 select-none">✈️</div>

        {/* Brand */}
        <h1 className="text-5xl font-bold text-white mb-2 tracking-tight">
          RouteCrafted
        </h1>
        <p className="text-blue-300 text-lg mb-6 font-medium">
          routecrafted.com
        </p>

        {/* Tagline */}
        <p className="text-blue-100 text-xl mb-10 leading-relaxed">
          AI-powered travel itinerary builder — day-by-day plans with
          weather-aware replanning and{" "}
          <span className="text-yellow-300 font-semibold">
            Worth It / Skip It
          </span>{" "}
          place cards.
        </p>

        {/* Coming Soon Badge */}
        <div className="inline-flex items-center gap-3 bg-blue-500/20 border border-blue-400/30 rounded-full px-7 py-3 mb-12">
          <span className="w-2.5 h-2.5 bg-green-400 rounded-full animate-pulse" />
          <span className="text-blue-100 font-semibold text-base tracking-wide">
            Coming Soon — In Development
          </span>
        </div>

        {/* Feature Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 text-center">
          <div className="bg-white/5 border border-white/10 rounded-2xl p-5 hover:bg-white/10 transition">
            <div className="text-3xl mb-3">🗺️</div>
            <p className="text-white font-semibold mb-1">AI Itineraries</p>
            <p className="text-blue-300 text-sm">
              Personalised day-by-day plans generated by Gemini AI
            </p>
          </div>
          <div className="bg-white/5 border border-white/10 rounded-2xl p-5 hover:bg-white/10 transition">
            <div className="text-3xl mb-3">⛅</div>
            <p className="text-white font-semibold mb-1">Weather Replanning</p>
            <p className="text-blue-300 text-sm">
              Auto-rewrites affected days when the forecast changes
            </p>
          </div>
          <div className="bg-white/5 border border-white/10 rounded-2xl p-5 hover:bg-white/10 transition">
            <div className="text-3xl mb-3">⭐</div>
            <p className="text-white font-semibold mb-1">Place Cards</p>
            <p className="text-blue-300 text-sm">
              Worth It / Skip It verdicts for every attraction
            </p>
          </div>
        </div>

        {/* Stack note */}
        <p className="mt-12 text-slate-500 text-sm">
          Built with Next.js 15 · Expo · Drizzle ORM · Neon · Gemini 2.0 Flash
        </p>
      </div>
    </main>
  );
}
